import { Question, Difficulty, GrammarPoint } from "./types";

export const mockQuestions: Question[] = [
  {
    id: "1",
    sentence: "______ tired, she still finished the report on time.",
    options: ["Although", "Because", "Unless", "Since"],
    correctIndex: 0,
    difficulty: Difficulty.Beginner,
    category: GrammarPoint.AdverbialClauses,
    explanation: {
      correctAnswer: "Although",
      rule: "Although is used to introduce a concessive adverbial clause, indicating a contrast between the two parts of the sentence.",
      example: "Although it was raining, they went for a walk.",
      commonMistake: "Using 'But' together with 'Although'. In English, we use one or the other, never both in the same sentence.",
    },
  },
  {
    id: "2",
    sentence: "The boy ______ is wearing a red hat is my brother.",
    options: ["which", "who", "whom", "whose"],
    correctIndex: 1,
    difficulty: Difficulty.Beginner,
    category: GrammarPoint.RelativeClauses,
    explanation: {
      correctAnswer: "who",
      rule: "We use 'who' as a relative pronoun to refer to people when it functions as the subject of the relative clause.",
      example: "The girl who won the race is my friend.",
      commonMistake: "Using 'which' for people. 'Which' is reserved for objects and animals.",
    },
  },
  {
    id: "3",
    sentence: "______ his homework, he went out to play football.",
    options: ["Finish", "Finished", "Having finished", "To finish"],
    correctIndex: 2,
    difficulty: Difficulty.Advanced,
    category: GrammarPoint.NonFiniteVerbs,
    explanation: {
      correctAnswer: "Having finished",
      rule: "The perfect participle (Having + past participle) is used to indicate that one action was completed before another action started.",
      example: "Having seen the movie before, I didn't want to go again.",
      commonMistake: "Using the simple 'Finished' which might imply a passive meaning or a state rather than a completed prior action.",
    },
  },
  {
    id: "4",
    sentence: "I don't know ______ he will come to the party or not.",
    options: ["if", "whether", "that", "which"],
    correctIndex: 1,
    difficulty: Difficulty.Intermediate,
    category: GrammarPoint.NounClauses,
    explanation: {
      correctAnswer: "whether",
      rule: "While 'if' and 'whether' can often be used interchangeably, 'whether' is preferred when followed by 'or not'.",
      example: "I'm not sure whether it will rain or not.",
      commonMistake: "Using 'that' when there is uncertainty. 'That' is used for facts or certainties.",
    },
  },
  {
    id: "5",
    sentence: "______ you work hard, you won't pass the exam.",
    options: ["If", "Unless", "As long as", "Once"],
    correctIndex: 1,
    difficulty: Difficulty.Beginner,
    category: GrammarPoint.Conditionals,
    explanation: {
      correctAnswer: "Unless",
      rule: "'Unless' means 'if... not'. It is used to introduce a negative condition.",
      example: "Unless it rains, we will have a picnic.",
      commonMistake: "Using 'Unless' with another negative word like 'don't', which creates a double negative.",
    },
  },
  {
    id: "6",
    sentence: "The city ______ I was born is very beautiful.",
    options: ["which", "that", "where", "who"],
    correctIndex: 2,
    difficulty: Difficulty.Intermediate,
    category: GrammarPoint.RelativeClauses,
    explanation: {
      correctAnswer: "where",
      rule: "'Where' is a relative adverb used to refer to a place when it functions as an adverbial of place in the relative clause.",
      example: "This is the house where I grew up.",
      commonMistake: "Using 'which' without a preposition (like 'in which') when referring to a location's function.",
    },
  },
  {
    id: "7",
    sentence: "I saw her ______ the piano when I passed her room.",
    options: ["play", "playing", "played", "to play"],
    correctIndex: 1,
    difficulty: Difficulty.Intermediate,
    category: GrammarPoint.NonFiniteVerbs,
    explanation: {
      correctAnswer: "playing",
      rule: "The present participle (-ing form) after verbs of perception (see, hear, watch) emphasizes an action in progress.",
      example: "I heard him singing in the shower.",
      commonMistake: "Using 'to play' after 'see'. We use either the bare infinitive (play) for the whole action or the -ing form for an action in progress.",
    },
  },
  {
    id: "8",
    sentence: "He spoke so fast ______ I couldn't understand him.",
    options: ["that", "which", "as", "than"],
    correctIndex: 0,
    difficulty: Difficulty.Beginner,
    category: GrammarPoint.AdverbialClauses,
    explanation: {
      correctAnswer: "that",
      rule: "The structure 'so + adjective/adverb + that' is used to express result.",
      example: "It was so cold that the lake froze.",
      commonMistake: "Using 'which' instead of 'that' in result clauses.",
    },
  },
];
